// GENERATED by tools/gen_sprites.cjs - sprite gfxoffsets
#ifndef SPRGFX_H
#define SPRGFX_H
#include <snes.h>

#define SHIP_GFX   0
#define BULLET_GFX 2

const u16 gfxA[24] = { 4, 8, 12, 256, 32, 36, 40, 264, 44, 64, 68, 320, 72, 76, 96, 328, 100, 104, 108, 384, 128, 132, 136, 392 };

const u16 gfxB[24] = { 6, 10, 14, 260, 34, 38, 42, 268, 46, 66, 70, 324, 74, 78, 98, 332, 102, 106, 110, 388, 130, 134, 138, 396 };

const u8  bigTier[4] = { 0, 0, 0, 1 };

#endif
