#!/usr/bin/env python3
# Build a HUD font SPRITE sheet from the (deadfall) hud_font.png for our Mode 7 game.
# We have no spare BG layer in Mode 7, so HUD text is drawn with sprites. Our OBJ size
# pair is 16/64 (no 8x8), so each 8x8 glyph is placed in the TOP-LEFT of a 16x16 sprite
# cell (rest transparent) and drawn as a 16x16 OBJ, spaced 8px so text reads normally.
#
# Outputs:
#   res/hudfont.png  -- indexed sprite sheet (convert with gfx4snes -s 16 -R)
#   src/hudfont.h    -- charGfx[ascii-32] -> sprite gfxoffset (font loads at VRAM tile 64)
#
#   python3 tools/gen_hudfont.py
from PIL import Image
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'res', 'hud_font.png')
CHARSET = "0123456789 SCOREHALT:#GMV"  # glyphs we need ('#' = custom bar block)
FONT_TILE = 160                       # font loads at VRAM tile 160 (after the far sprites)

src = Image.open(SRC).convert('L')
sp = src.load()

n = len(CHARSET)
ncell = ((n + 7) // 8) * 8                   # pad to full 8-cell VRAM bands
out = Image.new('P', (16, ncell * 16), 0)    # 16-wide, one 16x16 cell per glyph
out.putpalette([0, 0, 0] + [255, 255, 255] + [0, 0, 0] * 254)   # 0=transparent, 1=white
op = out.load()
for cell, ch in enumerate(CHARSET):
    if ch == '#':                            # custom solid block (health-bar segment)
        for y in range(1, 7):
            for x in range(1, 7):
                op[x, cell * 16 + y] = 1
        continue
    g = ord(ch) - 32                         # font is ascii 32..95, 16 cols x 4 rows
    c, r = g % 16, g // 16
    for y in range(8):
        for x in range(8):
            if sp[c * 8 + x, r * 8 + y] > 40:
                op[x, cell * 16 + y] = 1     # glyph in the cell's top-left 8x8
out.save(os.path.join(HERE, '..', 'hudfont.png'))

# gfxoffset of 16x16 cell K: 8 cells per VRAM band, +2 per cell, +32 per band, +base.
def cellgfx(k):
    return FONT_TILE + (k // 8) * 32 + (k % 8) * 2

tab = [0xFFFF] * 96                          # ascii 32..127 -> gfxoffset (0xFFFF = none)
for cell, ch in enumerate(CHARSET):
    tab[ord(ch) - 32] = cellgfx(cell)

h = "// GENERATED by tools/gen_hudfont.py - HUD font glyphs as 16x16 sprites\n"
h += "// charGfx[ascii-32] = sprite gfxoffset (0xFFFF = unsupported glyph)\n"
h += "#ifndef HUDFONT_H\n#define HUDFONT_H\n#include <snes.h>\n\n"
h += "const u16 charGfx[96] = { " + ", ".join(str(v) for v in tab) + " };\n\n"
h += "#endif\n"
with open(os.path.join(HERE, '..', 'src', 'hudfont.h'), 'w') as f:
    f.write(h)

print("wrote res/hudfont.png (%d cells) + src/hudfont.h" % n)
