// Generates ROM tables for placing entities in the tunnel (as a C header).
// Entities orbit WITH the tunnel when the world rotates, so position is computed
// from a screen ANGLE (which folds in worldRot + the in-progress spin) and a
// per-depth RADIUS, rather than a fixed lane->position table.
//
//   apothem[7]   : distance from tunnel center to a lane's face-midpoint per depth
//   faceAngle[6] : byte-angle (256 = 360deg) of each face's perpendicular
//   sintab[256]  : sin*127 (s8); cos(a) = sintab[(a+64)&255]
//   tierGfx[48]/tierBig[48] : depth (depth16>>5) -> sprite size tier
//
//   node tools/gen_entpos.cjs   ->   src/entpos.h
const fs = require('fs');
const path = require('path');

const A0 = 94;                         // bottom-edge apothem at depth 0 (screen px)
const scaleAt = (d) => 1 - 0.95 * Math.pow(d / 6, 0.5);

// radius (apothem) from tunnel center to a lane midpoint, per depth 0..6
const apo = [];
for (let d = 0; d < 7; d++) apo.push(Math.round(A0 * scaleAt(d)));

// face perpendicular angles: face F at 90 + F*60 deg (face 0 = straight down)
const faceAng = [];
for (let f = 0; f < 6; f++) faceAng.push(Math.round((90 + f * 60) / 360 * 256) & 0xFF);

// sin table, value = sin(angle)*127 in [-127,127]
const sintab = [];
for (let a = 0; a < 256; a++) sintab.push(Math.round(127 * Math.sin(a / 256 * 2 * Math.PI)));

// --- size-tier lookup (perspective-correct): depth16>>5 -> closest sprite tier 0..3 ---
// Tiers 0-2 are 16x16 (px ~8/12/16), tier 3 is 32x32 (~28px). main.c's sprgfx.h maps
// (type, tier) -> the actual sprite gfxoffset, so distinct per-type shapes plug in.
const TIERS_PX = [8, 12, 16, 28];
const MAXPX = 28, NLEV = 48;
const tidx = [];
for (let lvl = 0; lvl < NLEV; lvl++) {
  const target = MAXPX * scaleAt((lvl << 5) / 256);
  let best = 0, bd = 1e9;
  for (let i = 0; i < TIERS_PX.length; i++) { const dd = Math.abs(TIERS_PX[i] - target); if (dd < bd) { bd = dd; best = i; } }
  tidx.push(best);
}

let h = '// GENERATED by tools/gen_entpos.cjs\n';
h += '#ifndef ENTPOS_H\n#define ENTPOS_H\n#include <snes.h>\n\n';
h += `const u16 apothem[7]   = { ${apo.join(', ')} };\n\n`;
h += `const u8  faceAngle[6] = { ${faceAng.join(', ')} };\n\n`;
h += `const s8  sintab[256]  = { ${sintab.join(', ')} };\n\n`;
h += `const u8  tierIdx[${NLEV}] = { ${tidx.join(', ')} };\n\n`;
h += '#endif\n';

fs.writeFileSync(path.join(__dirname, '..', 'src', 'entpos.h'), h);
console.log(`wrote src/entpos.h (apothem ${apo.join(',')} | faceAngle ${faceAng.join(',')})`);
